- fix in checking is netforking is up.
Changed files:
    nwserv.init -> 1.2

diff --git a/nwserv.init b/nwserv.init
--- a/nwserv.init
+++ b/nwserv.init
@@ -14,7 +14,11 @@
 # Source function library.
 . /etc/rc.d/init.d/functions
 
-[ -x /usr/sbin/nwserv ] || exit 0
+# Check that networking is up.
+if [ "${NETWORKING}" = "no" ]; then
+	echo "WARNING: Networking is down. Nwserv service can't be runed."
+	exit 1
+fi
 
 # See how we were called.
 case "$1" in
